### ISSUE TITLE
[consistency] Document and reduce number of duplicated types

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-ts-sdk#117]
Looks like we have lots of duplicitous types:
MoveResourceType === MoveStructType, though one has docs another doesn’t
There’s a representation of a MoveModuleId and a ModuleId class, and a StructType which is a ModuleId plus a struct name
There’s also a representation of a FunctionId  which uses the StructType
It may be good to consolidate these in some way

Additionally, it would be good to document each accordingly.

**Comment by 0xjinn** [comment]
> Additionally, it would be good to document each accordingly.

Do we want to document them in code?
