### ISSUE TITLE
[Feature Request] Add ability to get Transaction Hash prior to submission

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-ts-sdk#200]
# 🚀 Feature Request Description

## Motivation
Hash should be accessible prior to submission to on chain. This should be applicable to both Python and Typescript SDKs.

**Comment by rondales** [comment]
> # 🚀 Feature Request Description
> ## Motivation
> Hash should be accessible prior to submission to on chain. This should be applicable to both Python and Typescript SDKs.

**Comment by 0xmaayan** [comment]
why not use simulation?
