### ISSUE TITLE
[Bug] Some properties not exist in Aptos client but could pass type check

### ISSUE THREAD

**Issue by SamuelQZQ** [aptos-labs/aptos-ts-sdk#243]
# 🐛 Bug Description

The `Aptos` class `extends` other class here:
https://github.com/aptos-labs/aptos-ts-sdk/blob/79996e697a712e7513815fc4741614bde6a3ef2d/src/api/aptos.ts#L62C1-L72C19

Which lead to this pass type check but couldn't run successfully:
```
const client = Aptos();
client.build.simple(...) // could pass type check, but will break because `build` not exist in `client`
```

## Expected Behavior

It should either pass type check and run successfully, or do not pass type check.

**Comment by 0xmaayan** [comment]
hmm it should be

```
client.transaction.build.simple(...)
```

take a look https://github.com/aptos-labs/aptos-ts-sdk?tab=readme-ov-file#single-signer-transaction

**Comment by SamuelQZQ** [comment]
@0xmaayan yes. But because of the `extends`, when input `client.` in IDE, `build` will also popup, and which isn't exist actually.

**Comment by SamuelQZQ** [comment]
Maybe that's because this `applyMixin ` not work correctly:
https://github.com/aptos-labs/aptos-ts-sdk/blob/79996e697a712e7513815fc4741614bde6a3ef2d/src/api/aptos.ts#L82C10-L82C20

**Comment by 0xmaayan** [comment]
> @0xmaayan yes. But because of the `extends`, when input `client.` in IDE, `build` will also popup, and which isn't exist actually.

I understand. You are welcome to submit a PR with a fix.
I will leave this issue open for tracking and will get back to it when have a bandwidth. 

> Maybe that's because this `applyMixin ` not work correctly: https://github.com/aptos-labs/aptos-ts-sdk/blob/79996e697a712e7513815fc4741614bde6a3ef2d/src/api/aptos.ts#L82C10-L82C20

The `Interface` is for the type check, and `applyMixin` is for the binding. The `Transaction` class is under the `transaction` namespace, and that is why it work for `client.transaction.build.simple(...)`
