### ISSUE TITLE
[Feature Request] Allow setting per-backend client config

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-ts-sdk#258]
When building `Aptos` you can provide a `ClientConfig` that is used for the underlying client when building requests.

It should be possible to provide a per-backend `ClientConfig` as well. So the final client config is the base client config with the per-backend config applied on top.

This way you can set different headers per backend, among other things.

**Comment by 0xmaayan** [comment]
@banool Thanks! Does the full `ClientConfig` type make sense per-backend config?
```
export type ClientConfig = {
  AUTH_TOKEN?: string;
  API_KEY?: string;
  HEADERS?: Record<string, string | number | boolean>;
  WITH_CREDENTIALS?: boolean;
};
```

**Comment by banool** [comment]
I think having both of these doesn't make sense, they're for different uses right?
```
AUTH_TOKEN?: string;
API_KEY?: string;
```

Maybe those need to split up into the per-backend configs or something?

**Comment by 0xmaayan** [comment]
Yea. `AUTH_TOKEN` is for faucet and `API_KEY` is part of the api gateway so node and indexer at the moment
