### ISSUE TITLE
Submit Transaction

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#273]
I'm following your guide to migrate from V1 to V2.

I couldn't find a way to submit my offline signed transaction using new api, i was trying 

`
await this.getClient().aptosClient.transaction.submit.simple({
  transaction: signedTransaction,
});
`

but its not working, how to submit a signed transaction using the new api?

thanks, dante

**Comment by 0xmaayan** [comment]
@dev-dantealighieri to submit a signed transaction you need the `signedTransaction` and the `senderAuthenticator`. 
```
await this.getClient().aptosClient.transaction.submit.simple({ transaction: signedTransaction, senderAuthenticator: senderSignature });
```

What is the exact flow you are working with? Maybe some of these examples will help
https://github.com/aptos-labs/aptos-ts-sdk/pull/257
https://github.com/aptos-labs/aptos-ts-sdk/tree/main/examples/typescript

**Comment by dev-dantealighieri** [comment]
yeah i see what i was looking for, thanks
