### ISSUE TITLE
TypeTagStruct for getting token in the new sdk

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#277]
I'm migrating to new sdk, couldn't find a way of doing the following snippet in the new sdk. Can provide a link to the specific documentation for this if it exists, or show the new way of doing this?

```
token = new TxnBuilderTypes.TypeTagStruct(
  TxnBuilderTypes.StructTag.fromString(assetName),
);
```

thanks, dante

**Comment by 0xmaayan** [comment]
@dev-dantealighieri Yes I think we are missing a helper `fromString` function in the new SDK. What you could do is
```
parseTypeTag(assetName)
```
That should return a `TypeTagStruct`. Can refer to https://github.com/aptos-labs/aptos-ts-sdk/blob/main/tests/unit/typeTagParser.test.ts#L168
