### ISSUE TITLE
INVALID SIGNATURE on simple transfer transaction

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#278]
```json
{
    "success": false,
    "message": "{\"message\":\"Invalid transaction: Type: Validation Code: INVALID_SIGNATURE\",\"error_code\":\"vm_error\",\"vm_error_code\":1}",
    "stack": "AptosApiError: {\"message\":\"Invalid transaction: Type: Validation Code: INVALID_SIGNATURE\",\"error_code\":\"vm_error\",\"vm_error_code\":1}\n    at Gt (/Users/dante/Documents/Codes/apt-v5/node_modules/@aptos-labs/ts-sdk/src/client/post.ts:74:9)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at fn (/Users/dante/Documents/Codes/apt-v5/node_modules/@aptos-labs/ts-sdk/src/internal/digitalAsset.ts:344:5)\n   ....
}
```

I'm creating simple transfer using new sdk, and using external signing, with %50 percent change, my transaction is rejected with invalid signature error, i couldnt figure out whats the reason for this, what would be the reason for this?

after externally signing the transaction, im building the transaction again using the `aptosClient.transaction.build.simple()` with same parameters, and get rawTransaction from it and create the signed transaction as following

```typescript
 // signing transaction and getting signature above, then

 aptosClient.transaction.build.simple(...);

 const { rawTransaction } = simpleTransaction;

  const authenticator = new TransactionAuthenticatorEd25519(
    new Ed25519PublicKey(publicKey),
    signature,
  );

  const signedTransaction = new SignedTransaction(
    rawTransaction,
    authenticator,
  );
```

what might be the problem in my situation.

I tried to broadcast same signedTransaction couple of times, its not accepted by node and getting invalid signature error until i create a new transaction from scratch in this situation.

**Comment by dev-dantealighieri** [comment]
I assume its because im using `aptosClient.transaction.build.simple`, how can i create trasnaction manually from scratch? can you provide examples because i cant find in documentation.

**Comment by 0xmaayan** [comment]
@dev-dantealighieri `aptosClient.transaction.build.simple` uses `buildTransaction` so you might end up with the same result. Invalid signature can happen in different cases, could you share a bit more about the flow you are trying to achieve? is this a sponsor transaction? is there only one signer?

**Comment by dev-dantealighieri** [comment]
this is one signer, and im doing external signing, and yes you are correct, i am still getting `INVALID_SIGNATURE` error sometimes.

this is simple transfer transaction. im creating it like the following

```typescript
const simpleTransactionOffline = await buildTransaction({
  aptosConfig: aptosClient.config,
  sender: address,
  payload: await generateTransactionPayload({
    aptosConfig: aptosClient.config,
    function: '0x1::coin::transfer',
    typeArguments: [token],
    functionArguments: [
      address,
      amount
    ],
  }),
  options: {
    accountSequenceNumber,
    expireTimestamp,
    // gasUnitPrice,
    maxGasAmount: maxGasAmount,
    // gasUnitPrice,
  },
});
```

im using the following signer

```
import * as EC from 'elliptic';
const ec = new EC.eddsa('ed25519');
```

no idea why im getting this error. 

thanks for your help.

**Comment by 0xmaayan** [comment]
I see. could you take a look on this `external_signing` example? https://github.com/aptos-labs/aptos-ts-sdk/blob/main/examples/typescript/external_signing.ts

**Comment by dev-dantealighieri** [comment]
i already did, im doing the same things, still get this error sometimes, what might be the reason to get this error?

**Comment by 0xmaayan** [comment]
How do you generate the sender? using the SDK or `const ec = new EC.eddsa('ed25519');`? it might be that you use 2 different signing schemes?

**Comment by dev-dantealighieri** [comment]
it wasnt about this, i am not sure how but now its working, thanks!
