### ISSUE TITLE
calculating transaction cost without simulation

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#279]
i have two questions,

first one is, i want my transaction to be executed no matter what, should i calculate gas price for this transaction before broadcasting it, or is broadcasting it with default values enough for this?

second question is, i saw the transaction simulation concept, can we calculate how much gas will my transaction use without broadcasting a simulation transaction, and what is the current gas price on the blockchain, can we see that without creating a simulation transaction?

**Comment by dev-dantealighieri** [comment]
i tried `aptosClient.transaction.simulate.simple` and its returning gas_used and gas_unit_price fields, how can i interpret these values and broadcast the transaction

<img width="1022" alt="image" src="https://github.com/aptos-labs/aptos-ts-sdk/assets/156019107/d5427d71-c36c-46e3-a314-ff811b857c8b">

**Comment by dev-dantealighieri** [comment]
i tried `aptosClient.transaction.simulate.simple` and its returning these fields

<img width="168" alt="image" src="https://github.com/aptos-labs/aptos-ts-sdk/assets/156019107/2832d7f5-37b9-457a-8724-44f2460cce95">

are these values okey to use instead the maxGasAmount and gasUnitPrice fields of transaction?

**Comment by dev-dantealighieri** [comment]
first of all thank you very much for your answers!

https://aptos.dev/concepts/gas-txn-fee/#simulation-steps

from here what i understand is, i should simulate, get the gas_used, multiply with safety factor, if its lower than max_gas_amount, use the gas_used.

am i correct?

thanks, dante

**Comment by dev-dantealighieri** [comment]
what happens when we dont set gas unit price and max gas amount, are they set to default values?

**Comment by 0xmaayan** [comment]
Yes, SDK sets default values when generating the transaction https://github.com/aptos-labs/aptos-ts-sdk/blob/main/src/transactions/transactionBuilder/transactionBuilder.ts#L234-L236
