### ISSUE TITLE
[Feature Request] Support indexer on custom network

### ISSUE THREAD

**Issue by 0xaptosj** [aptos-labs/aptos-ts-sdk#282]
# 🚀 Feature Request Description

## Motivation

SDK handels indexer request specially [here](https://github.com/aptos-labs/aptos-ts-sdk/blob/8d28c1a833b18be0fd9bd76d5b19d9c66ac14e07/src/client/core.ts#L84-L98), but currently `isIndexerRequest` only works on known networks (e.g. mainnet, testnet, devnet, randomnet, localnet), if user enters a custom network, this code block will be skipped, leading to indexer request always return undefined due to incorrect parsing. 

We need to fix it.

## Pitch

**Describe the solution you would like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by 0xmaayan** [comment]
> if user enters a custom network, this code block will be skipped, leading to indexer request always return undefined due to incorrect parsing

I think we can assume that if user uses a custom network, and not an Aptos network, it is expected from the SDK to not handle it as an Aptos network. We cant really know the format this custom network returns the data in, so we just return it as is.

**Comment by 0xaptosj** [comment]
> > if user enters a custom network, this code block will be skipped, leading to indexer request always return undefined due to incorrect parsing
> 
> I think we can assume that if user uses a custom network, and not an Aptos network, it is expected from the SDK to not handle it as an Aptos network. We cant really know the format this custom network returns the data in, so we just return it as is.

I agree, but [this line](https://github.com/aptos-labs/aptos-ts-sdk/blob/f09ddbf9ed8d0a9e05d87af7e3c2b19de8394112/src/internal/account.ts#L338) makes it always return undefined when using custom network.

**Comment by 0xmaayan** [comment]
> > > if user enters a custom network, this code block will be skipped, leading to indexer request always return undefined due to incorrect parsing
> > 
> > 
> > I think we can assume that if user uses a custom network, and not an Aptos network, it is expected from the SDK to not handle it as an Aptos network. We cant really know the format this custom network returns the data in, so we just return it as is.
> 
> I agree, but [this line](https://github.com/aptos-labs/aptos-ts-sdk/blob/f09ddbf9ed8d0a9e05d87af7e3c2b19de8394112/src/internal/account.ts#L338) makes it always return undefined when using custom network.

you're right. so the SDK gives custom network support but not really... like you can query but not sure you would get the data correctly. We have some options then

- Make the SDK to be fully generic, which is a big lift and not sure we want to go that road
- Define an API standard (unrelated to the SDK)
- Agree that this is the format the SDK supports for indexer/fullnode responses, if you use a custom server you should conform to that structure.

btw, sdk does a parsing job to align with Aptos' indexer. Originally indexer returns `data.data.<whatever>`, the sdk parses it to `data.<whatever>`

**Comment by gregnazario** [comment]
> > > > if user enters a custom network, this code block will be skipped, leading to indexer request always return undefined due to incorrect parsing
> > > 
> > > 
> > > I think we can assume that if user uses a custom network, and not an Aptos network, it is expected from the SDK to not handle it as an Aptos network. We cant really know the format this custom network returns the data in, so we just return it as is.
> > 
> > 
> > I agree, but [this line](https://github.com/aptos-labs/aptos-ts-sdk/blob/f09ddbf9ed8d0a9e05d87af7e3c2b19de8394112/src/internal/account.ts#L338) makes it always return undefined when using custom network.
> 
> you're right. so the SDK gives custom network support but not really... like you can query but not sure you would get the data correctly. interesting....
> 
> Guess we have some options then
> 
> * Make the SDK to be fully generic, which is a big lift and not sure we want to go that road
> * Define an API standard (unrelated to the SDK)
> * Agree that this is the format the SDK supports for indexer/fullnode responses, if you use a custom server you should conform to that structure.
> 
> btw, sdk does a parsing job to align with Aptos' indexer. Originally indexer returns `data.data.<whatever>`, the sdk parses it to `data.<whatever>`

I think we can be opinionated here, and only support custom indexers that use the indexer platform in the `aptos-core/indexer-processors` repo.

None of the existing functionality may work if the custom indexer being used doesn't have the same schema, and since both are under the `aptos-labs`

**Comment by gregnazario** [comment]
Indexer requests now work correctly with custom indexers https://github.com/aptos-labs/aptos-ts-sdk/blob/main/src/api/aptosConfig.ts#L103-L126

https://github.com/aptos-labs/aptos-ts-sdk/blob/main/src/client/core.ts#L75-L88
