### ISSUE TITLE
coin transfer fails

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#286]
hi

im trying to send some zUSDC token to another account, which doesn't have any of it, and its now shown in target wallet too.

when im trying to send this transaction, i get the following error.

```
status: ❌ fail
VM status: Move abort in 0x1::coin: ECOIN_STORE_NOT_PUBLISHED(0x60005): Account hasn't registered `CoinStore` for `CoinType`
```

i'm creating the tx as follows

```typescript
const payload = await generateTransactionPayload({
  aptosConfig,
  function: "0x1::coin::transfer",
  typeArguments: ["0xf22bede237a07e121b56d91a491eb7bcdfd1f5907926a9e58338f964a01b17fa::asset::USDC"],
  functionArguments: [address, amount],
});

const transaction = await buildTransaction({
  aptosConfig,
  sender: senderAddress,
  payload: payload,
  options: {
    accountSequenceNumber: nonce,
    expireTimestamp: expireAt,
  },
});
```

im using 
`maxGasAmount = 2000`
`gasUnitPrice = 150`

how can i send an asset that doesn't appear on the receiving side?

thanks, dante

**Comment by gregnazario** [comment]
Hi, you can use the function `0x1::aptos_account::transfer_coins` with the same exact inputs.  It will create the coinstore on the receiving side

**Comment by dev-dantealighieri** [comment]
thanks!
