### ISSUE TITLE
[Feature Request] add SDK support of a new transaction type: ValidatorTransaction

### ISSUE THREAD

**Issue by zjma** [aptos-labs/aptos-ts-sdk#289]
# 🚀 Feature Request Description

Add SDK support of a new transaction type: ValidatorTransaction.

## Motivation

`ValidatorTransaction`s ([node API](https://github.com/aptos-labs/aptos-core/blob/b4fbf4cb55fd85bcd617ce33158db4fe40e7db35/api/types/src/transaction.rs#L180), [AIP](https://github.com/aptos-foundation/AIPs/pull/274/files)) are designed to be only proposed by validators to publish system-level resources.
It's a building block of ZKID, on-chain randomness (and perhaps more things in the future).

1.10 release will be its debut, and therefore when SDK support is needed.

**Comment by 0xmaayan** [comment]
@zjma could you clarify the SDK requirements? 
- Does the SDK need to support read and write `ValidatorTransaction` operations?
- If write, could you share code snippets to how a `ValidatorTransaction` should be constructed?

**Comment by zjma** [comment]
@0xmaayan i assume write = submit a txn?

If so, only read support is needed. This new type of txns is only proposed by validators.
