### ISSUE TITLE
details of tokens

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#290]
hi, is there a way to get decimals of a token using sdk?

thanks, dante

**Comment by 0xmaayan** [comment]
The `decimal` field was not exposed on the Indexer side. We just exposed it and will regenerate the scheme on the SDK side and publish a new version with that field exposed.

Thanks for reporting!

**Comment by dev-dantealighieri** [comment]
thanks!
