### ISSUE TITLE
TransactionResponseType for transfer transactions

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#298]
hi,

im only interested in token and native coin transactions when im indexing data. currently i program with typescript, i get some errors because i use `TransactionResponse` for tx types, but it is a union type that has lots of types in it.

```ts
declare enum TransactionResponseType {
    Pending = "pending_transaction",
    User = "user_transaction",
    Genesis = "genesis_transaction",
    BlockMetadata = "block_metadata_transaction",
    StateCheckpoint = "state_checkpoint_transaction"
}
```

is it enough for me to just cover `TransactionResponseType.User` type for transfer transactions, and `TransactionResponseType.Pending` for pending ones?

thanks, dante

**Comment by 0xmaayan** [comment]
What errors are you getting? Yes those transaction types should cover your use case

**Comment by Caczo** [comment]
Try using a different language or finding a bug

**Comment by dev-dantealighieri** [comment]
thanks genius 👍
