### ISSUE TITLE
coin registery in payload

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#299]
hi,

I'm trying to send a coin to an account that doesn't have that token, I'm getting the following error.

Move abort in 0x1::coin: ECOIN_STORE_NOT_PUBLISHED(0x60005): Account hasn't registered `CoinStore` for `CoinType`

how can i adjust my code to that situation?

```ts
  const isCoinRegistery = true; // what to do next?

  return generateTransactionPayload({ // this function is coming from the new ts sdk
    aptosConfig,
    function: '0x1::coin::transfer',
    typeArguments: [token]
    functionArguments: [address, amount],
  });
```

thanks, dante

**Comment by dev-dantealighieri** [comment]
I also tried `0x1::managed_coin::register` as function, but its giving the following error

'Error: Too many arguments for '0x1::managed_coin::register', expected 0

**Comment by 0xmaayan** [comment]
Has the receiver account created on chain? try use `0x1::aptos_account::transfer_coins` that would first create the account and then transfer. https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/aptos_account.move#L98C22-L98C36

**Comment by dev-dantealighieri** [comment]
account is created on chain, now im trying to send a token that doesnt exist on receiving side, but i got the following error:

Move abort in 0x1::coin: ECOIN_STORE_NOT_PUBLISHED(0x60005): Account hasn't registered CoinStore for CoinType

I tested by sending more gas, its not related to that btw

thanks

**Comment by dev-dantealighieri** [comment]
should the receiving side register by themselfs? this is the only possible thinks i can see now.

**Comment by 0xmaayan** [comment]
Try the entry function I linked - "This would create the recipient account first and register it to receive the CoinType, before transferring"

**Comment by dev-dantealighieri** [comment]
I dont want to create the recipient, i want to transfer a token to some account, but that coin is not registered there, can i register that coin for them with some option/function, or should they required to register that coin for themselves?

**Comment by dev-dantealighieri** [comment]
i think i found the answer, you need to use `"0x1::aptos_account::transfer_coins"` in order to send tokens, and `"0x1::aptos_account::transfer"` for native aptos coin.
