### ISSUE TITLE
[Feature Request] `aptos.view` requires the function args to be `String`

### ISSUE THREAD

**Issue by BriungRi** [aptos-labs/aptos-ts-sdk#347]
# 🚀 Feature Request Description

Support `AccountAddress` as an argument type in `aptos.view`

## Motivation

`AccountAddress` abstraction is nice because it helps ensure that we are working with an account address and not an arbitrary String. However, `aptos.view` only supports `String` type, so any `AccountAddress` needs to call `toString`. It is also not clear that only `String` works, so this doesn't get surfaced until a developer runs into a bug.

**Comment by gregnazario** [comment]
The latest version of the SDK is a breaking change that uses BCS for view functions rather than string.  Can you try 1.11?

**Comment by gregnazario** [comment]
There are now two functions for this:
`view` which uses BCS arguments (like AccountAddress)
`viewJson` which uses the original JSON arguments

https://github.com/aptos-labs/aptos-ts-sdk/blob/main/src/api/general.ts#L112-L156
