### ISSUE TITLE
can't connect to another node

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#372]
following code demonstrates how I try to connect a specific node, however i cannot achieve this.

```ts
      const config = new AptosConfig({
        network: Network.MAINNET, // ?
        fullnode: nodeUrl,
      });
      const aptosClient = new Aptos(config);
```

I've tried `https://fullnode.mainnet.aptoslabs.com/`, `https://fullnode.testnet.aptoslabs.com/`, but couldn't get a response from node. My questions are:

1) How should I connect to a custom node?
2) Which port should I connect, is it 8080?
3) Do i need to specify network type as mainnet if i've already gave fullnode url?

thanks, dante

**Comment by 0xmaayan** [comment]
Hi @dev-dantealighieri, first to use `https://fullnode.mainnet.aptoslabs.com/` or `https://fullnode.testnet.aptoslabs.com/` needs to append `v1` at the end, so should use it like that `https://fullnode.mainnet.aptoslabs.com/v1`.
Note that when using `Network.MAINNET` or `Network.TESTNET` the sdk uses those endpoints by default so you dont need to define as a custom node.

If you want to use a custom node, for example `https://my.custom.node.com/`, you have configured it correctly
```
const config = new AptosConfig({
  network: Network.MAINNET, 
  fullnode:"https://my.custom.node.com/",
});
const aptosClient = new Aptos(config);
```
Doing that, the sdk would use the `custom` node when doing `fullnode requests`, but for all other requests (indexer/faucet) the sdk would use `mainnet` endpoint

**Comment by dev-dantealighieri** [comment]
for example if my node ip is `10.20.30.40`, how should i connect? which port should i use?

**Comment by 0xmaayan** [comment]
depends how you configured your server/node. You can use aptos cli to [run a local network](https://aptos.dev/tools/aptos-cli/use-cli/running-a-local-network) (which runs on `http://localhost:8080/v1`)

**Comment by 0xmaayan** [comment]
Is `nodeip:8080/v1` a custom node that runs locally? are you sure this is the endpoint the node expects you to hit?
