### ISSUE TITLE
abi-function vector can not be parse[Bug] <Bug Title>

### ISSUE THREAD

**Issue by leverwwz** [aptos-labs/aptos-ts-sdk#373]
# 🐛 Bug Description
sir, not sure is it a bug or something wrong,please help check the following error.

latest sdk:can not parse vector<T>
====================
transaction.build.simple()

Error: Type mismatch for argument 3, type 'vector<u8>'
===========================
"{\"arguments\":[\"200000000\",\"103442574815287917127754190030147459068000000000000000000000001712900110170\",\"00000000000000000000000000\",{\"60\":49,\"47\":18,\"54\":169,\"61\":250,\"48\":13,\"55\":41,\"62\":52,\"49\":233,\"56\":161,\"63\":7,\"57\":111,\"58\":161,\"0\":34,\"59\":138,\"1\":231,\"2\":29,\"3\":123,\"4\":86,\"5\":93,\"6\":33,\"7\":244,\"10\":153,\"8\":208,\"9\":255,\"11\":127,\"12\":6,\"13\":161,\"20\":228,\"21\":202,\"14\":136,\"22\":127,\"15\":102,\"30\":50,\"23\":8,\"16\":204,\"31\":2,\"24\":201,\"17\":3,\"32\":67,\"25\":10,\"18\":82,\"40\":223,\"33\":46,\"26\":204,\"19\":191,\"41\":49,\"34\":240,\"27\":159,\"42\":211,\"35\":95,\"28\":77,\"43\":152,\"50\":242,\"36\":251,\"29\":165,\"44\":244,\"51\":207,\"37\":143,\"45\":197,\"52\":81,\"38\":111,\"46\":75,\"39\":228,\"53\":105},2],\"type_arguments\":[\"0x1::aptos_coin::AptosCoin\"],\"function\":\"0xd00a39c54ebe233d36dc67fcb63316c6dbf3cd14c4fe9a9c4824b5b9e3a739a3::buy::buy_entry\",\"type\":\"entry_function_payload\"}",

===========================
abi
"{\"abi\":{\"structs\":[{\"fields\":[{\"name\":\"buyer_address\",\"type\":\"address\"},{\"name\":\"token_payment\",\"type\":\"0x1::string::String\"},{\"name\":\"order_id\",\"type\":\"u256\"},{\"name\":\"campaign_id\",\"type\":\"u256\"},{\"name\":\"amount\",\"type\":\"u64\"},{\"name\":\"timestamp\",\"type\":\"u64\"}],\"is_native\":false,\"name\":\"BuyEvent\",\"abilities\":[\"drop\",\"store\"],\"generic_type_params\":[]},{\"fields\":[{\"name\":\"amount\",\"type\":\"u64\"},{\"name\":\"payment_token\",\"type\":\"0x1::string::String\"},{\"name\":\"buyer\",\"type\":\"address\"},{\"name\":\"campaign_id\",\"type\":\"u256\"}],\"is_native\":false,\"name\":\"BuyOrder\",\"abilities\":[\"copy\",\"drop\",\"store\",\"key\"],\"generic_type_params\":[]},{\"fields\":[{\"name\":\"treasury\",\"type\":\"address\"},{\"name\":\"admin_pubkey\",\"type\":\"vector<u8>\"},{\"name\":\"orders\",\"type\":\"0x1::smart_table::SmartTable<u256, 0xd00a39c54ebe233d36dc67fcb63316c6dbf3cd14c4fe9a9c4824b5b9e3a739a3::buy::BuyOrder>\"},{\"name\":\"campaigns\",\"type\":\"0x1::smart_table::SmartTable<u256, bool>\"},{\"name\":\"usedOrders\",\"type\":\"0x1::smart_table::SmartTable<u256, bool>\"},{\"name\":\"accepted_token\",\"type\":\"0x1::smart_table::SmartTable<0x1::string::String, bool>\"}],\"is_native\":false,\"name\":\"BuyOrders\",\"abilities\":[\"store\",\"key\"],\"generic_type_params\":[]}],\"friends\":[],\"name\":\"buy\",\"exposed_functions\":[{\"is_view\":false,\"params\":[\"&signer\",\"0x1::string::String\"],\"return\":[],\"generic_type_params\":[],\"is_entry\":true,\"name\":\"add_accepted_token\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"u64\",\"u256\",\"u256\",\"vector<u8>\",\"u8\"],\"return\":[],\"generic_type_params\":[{\"constraints\":[]}],\"is_entry\":false,\"name\":\"buy\",\"visibility\":\"public\"},{\"is_view\":true,\"params\":[],\"return\":[\"address\"],\"generic_type_params\":[],\"is_entry\":false,\"name\":\"buy_address\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"u64\",\"u256\",\"u256\",\"vector<u8>\",\"u8\"],\"return\":[],\"generic_type_params\":[{\"constraints\":[]}],\"is_entry\":true,\"name\":\"buy_entry\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"0x1::string::String\"],\"return\":[],\"generic_type_params\":[],\"is_entry\":true,\"name\":\"deactive_accepted_token\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"u256\"],\"return\":[],\"generic_type_params\":[],\"is_entry\":true,\"name\":\"deactive_campaign_entry\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"address\",\"vector<u8>\"],\"return\":[],\"generic_type_params\":[],\"is_entry\":true,\"name\":\"initialize\",\"visibility\":\"public\"},{\"is_view\":true,\"params\":[],\"return\":[\"bool\"],\"generic_type_params\":[],\"is_entry\":false,\"name\":\"is_initialized\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"u256\"],\"return\":[],\"generic_type_params\":[],\"is_entry\":true,\"name\":\"regist_campaign_entry\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"vector<u8>\"],\"return\":[],\"generic_type_params\":[],\"is_entry\":true,\"name\":\"set_admin_pubkey_entry\",\"visibility\":\"public\"},{\"is_view\":false,\"params\":[\"&signer\",\"address\"],\"return\":[],\"generic_type_params\":[],\"is_entry\":true,\"name\":\"set_treasury_entry\",\"visibility\":\"public\"}],\"address\":\"0xd00a39c54ebe233d36dc67fcb63316c6dbf3cd14c4fe9a9c4824b5b9e3a739a3\"}}"

## How to reproduce

**Code snippet to reproduce**
```typescript
// Your code goes here 
// Please make sure to list any dependencies
```

**Stack trace / error message**
```
// Paste the output here
```

## System information

**System details:**
- Typescript SDK Version
- Platform (e.g. Node, browser, etc.)

**Comment by 0xmaayan** [comment]
To send a vector type argument using the SDK you should have it as an array

```
const txn = await aptos.transaction.build.simple({
    sender: account.accountAddress,
    data: {
      function: "0xd00a39c54ebe233d36dc67fcb63316c6dbf3cd14c4fe9a9c4824b5b9e3a739a3::buy::buy_entry",
      typeArguments: ["0x1::aptos_coin::AptosCoin"],
      functionArguments: [
        "200000000",
        "103442574815287917127754190030147459068000000000000000000000001712900110170",
        "00000000000000000000000000",
        [6], // vector is an array
        2,
      ],
    },
  });
```

**Comment by leverwwz** [comment]
> To send a vector type argument using the SDK you should have it as an array
> 
> ```
> const txn = await aptos.transaction.build.simple({
>     sender: account.accountAddress,
>     data: {
>       function: "0xd00a39c54ebe233d36dc67fcb63316c6dbf3cd14c4fe9a9c4824b5b9e3a739a3::buy::buy_entry",
>       typeArguments: ["0x1::aptos_coin::AptosCoin"],
>       functionArguments: [
>         "200000000",
>         "103442574815287917127754190030147459068000000000000000000000001712900110170",
>         "00000000000000000000000000",
>         [6], // vector is an array
>         2,
>       ],
>     },
>   });
> ```

sure, em.......sir, i tried array but not work.
aptos-sdk v2
==============err log
item.serialize is not a function
TypeError: item.serialize is not a function
===========================
 serializeVector<T extends Serializable>(values: Array<T>): void {
    this.serializeU32AsUleb128(values.length);
    values.forEach((item) => {
      item.serialize(this);
    });
  }

**Comment by leverwwz** [comment]
> What does your array contain? I am not sure what that supposed to be
> 
> ```
> "60":49,"47":18,"54":169,"61":250,"48":13,"55":41,"62":52,"49":233,"56":161,"63":7,"57":111,"58":161,"0":34,"59":138,"1":231,"2":29,"3":123,"4":86,"5":93,"6":33,"7":244,"10":153,"8":208,"9":255,"11":127,"12":6,"13":161,"20":228,"21":202,"14":136,"22":127,"15":102,"30":50,"23":8,"16":204,"31":2,"24":201,"17":3,"32":67,"25":10,"18":82,"40":223,"33":46,"26":204,"19":191,"41":49,"34":240,"27":159,"42":211,"35":95,"28":77,"43":152,"50":242,"36":251,"29":165,"44":244,"51":207,"37":143,"45":197,"52":81,"38":111,"46":75,"39":228,"53":105
> ```
> 
> I an able to build a transaction with the snippet I shared

ok, sir  can u help shere some demo about this?  
show how to use vector in aptos-sdk v2?

**Comment by 0xmaayan** [comment]
> > What does your array contain? I am not sure what that supposed to be
> > ```
> > "60":49,"47":18,"54":169,"61":250,"48":13,"55":41,"62":52,"49":233,"56":161,"63":7,"57":111,"58":161,"0":34,"59":138,"1":231,"2":29,"3":123,"4":86,"5":93,"6":33,"7":244,"10":153,"8":208,"9":255,"11":127,"12":6,"13":161,"20":228,"21":202,"14":136,"22":127,"15":102,"30":50,"23":8,"16":204,"31":2,"24":201,"17":3,"32":67,"25":10,"18":82,"40":223,"33":46,"26":204,"19":191,"41":49,"34":240,"27":159,"42":211,"35":95,"28":77,"43":152,"50":242,"36":251,"29":165,"44":244,"51":207,"37":143,"45":197,"52":81,"38":111,"46":75,"39":228,"53":105
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I an able to build a transaction with the snippet I shared
> 
> ok, sir can u help shere some demo about this? show how to use vector in aptos-sdk v2?

This is how you use a vector with this `@aptos-labs/ts-sdk` package (i.e aptos ts sdk v2)

```
const txn = await aptos.transaction.build.simple({
    sender: account.accountAddress,
    data: {
      function: "my::function::address"
      functionArguments: [
        [6,2,3], // this is a vector of numbers
        ["hi","hello"], // this is a vector of strings
        [true,false], // this is a vector of booleans
      ],
    },
  });
```

**Comment by leverwwz** [comment]
> > > What does your array contain? I am not sure what that supposed to be
> > > ```
> > > "60":49,"47":18,"54":169,"61":250,"48":13,"55":41,"62":52,"49":233,"56":161,"63":7,"57":111,"58":161,"0":34,"59":138,"1":231,"2":29,"3":123,"4":86,"5":93,"6":33,"7":244,"10":153,"8":208,"9":255,"11":127,"12":6,"13":161,"20":228,"21":202,"14":136,"22":127,"15":102,"30":50,"23":8,"16":204,"31":2,"24":201,"17":3,"32":67,"25":10,"18":82,"40":223,"33":46,"26":204,"19":191,"41":49,"34":240,"27":159,"42":211,"35":95,"28":77,"43":152,"50":242,"36":251,"29":165,"44":244,"51":207,"37":143,"45":197,"52":81,"38":111,"46":75,"39":228,"53":105
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I an able to build a transaction with the snippet I shared
> > 
> > 
> > ok, sir can u help shere some demo about this? show how to use vector in aptos-sdk v2?
> 
> This is how you use a vector with this `@aptos-labs/ts-sdk` package (i.e aptos ts sdk v2)
> 
> ```
> const txn = await aptos.transaction.build.simple({
>     sender: account.accountAddress,
>     data: {
>       function: "my::function::address"
>       functionArguments: [
>         [6,2,3], // this is a vector of numbers
>         ["hi","hello"], // this is a vector of strings
>         [true,false], // this is a vector of booleans
>       ],
>     },
>   });
> ```

ok i think this is good enough, thank u so much.

**Comment by gregnazario** [comment]
Additionally, this looks like since it's a vector u8, you should be able to pass uint8array for that value
