### ISSUE TITLE
[Bug] I encountered an error when trying to fetch the list of collections by getAccountCollectionsWithOwnedTokens

### ISSUE THREAD

**Issue by ducnguyen993** [aptos-labs/aptos-ts-sdk#434]
# 🐛 Bug Description

## How to reproduce

**Code snippet to reproduce**
```typescript
const alice = Account.fromPrivateKey({
    privateKey: new Ed25519PrivateKey("507b4df2baa236ec488ccba435b7594add722ff5c2f5836291b5bd899cf902af"),
  });
  console.log("=== Addresses ===\n");
  console.log(`Alice's address is: ${alice.accountAddress}`);
  const alicesCollection = await aptos.getAccountCollectionsWithOwnedTokens({
    accountAddress: alice.accountAddress,
  });
```

**Stack trace / error message**
```
AptosApiError: Indexer error: field 'amount' not found in type: 'current_collection_ownership_v2_view_bool_exp'
```

## System information

**System details:**
- Typescript SDK Version
- Platform (e.g. Node, browser, etc.)

**Comment by ducnguyen993** [comment]
Hey @gregnazario , another error when I try to use this function

`[AptosApiError: Indexer error: Unhandled Error 408 : undefined]`

**Comment by gregnazario** [comment]
> Hey @gregnazario , another error when I try to use this function
> 
> 
> 
> `[AptosApiError: Indexer error: Unhandled Error 408 : undefined]`

Which network is this using?  Devnet?
