### ISSUE TITLE
[Feature Request] Decouple `getAccountCoinAmount` from indexer

### ISSUE THREAD

**Issue by 0xbe1** [aptos-labs/aptos-ts-sdk#459]
# 🚀 Feature Request Description

Instead we can simply call view function and fetch the exact same result, and view function is more reliable than indexer

## Motivation

**Is your feature request related to a problem? Please describe you use case.**

We ran into an issue that we call `getAccountCoinAmount` that returned 0 incorrectly due to indexer issue. This can be avoided if `getAccountCoinAmount` calls into view function `0x1::coin::balance` or `0x1::fungible_asset::balance` directly.

**Comment by 0xmaayan** [comment]
agreed. wanted to make that change but didnt have the bandwidth for that, also need to think on how we handle coin vs fungible asset correctly.

Are you willing to create a PR with a change?

**Comment by SamuelQZQ** [comment]
@0xmaayan sure, we will create a PR.

**Comment by alex4506** [comment]
https://github.com/aptos-labs/aptos-ts-sdk/pull/519
