### ISSUE TITLE
getting transaction hash from deserialized transaction

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-ts-sdk#487]
```typescript
  const buffer = Buffer.from(signedTransaction, 'hex');

  const deserializedRawSignedTransaction = SignedTransaction.deserialize(
    new Deserializer(buffer),
  );

  // tx hash offline
  // ?
```

I am using `aptos typescript sdk 1.7.0` how can I get transaction hash offline after deserialization? I guess in the new versions you have a function for that but I cannot upgrade my sdk version, I need to find a way, thanks in advance.

**Comment by 0xmaayan** [comment]
Hi @dev-dantealighieri , the SDK exports a [generateUserTransactionHash](https://github.com/aptos-labs/aptos-ts-sdk/blob/main/src/transactions/transactionBuilder/transactionBuilder.ts#L544) function to generate the transaction hash off-chain. If you can't upgrade to the newer version, you could copy the method logic.

**Comment by dev-dantealighieri** [comment]
thanks, thats how I did it!
