### ISSUE TITLE
[Feature Request] Proxy Support

### ISSUE THREAD

**Issue by incognito243** [aptos-labs/aptos-ts-sdk#558]
# 🚀 Feature Request Description

## Motivation

i have problem and need to use proxy to solvI'm facing an issue and need to use a proxy to resolve it, but I'm unsure if this SDK has proxy support options available.

**Comment by incognito243** [comment]
Could you support me in this case? @0xmaayan

**Comment by 0xmaayan** [comment]
Hi, could you elaborate more on the issue you are having?

**Comment by 0xmaayan** [comment]
Oh if you want to use your own client, like @nhd98z suggests, you can use it like that in the SDK https://github.com/aptos-labs/aptos-ts-sdk/blob/main/examples/typescript/custom_client.ts

**Comment by incognito243** [comment]
Actually, I want to implement an HTTP proxy agent, and the client will communicate with the node through it.

**Comment by 0xmaayan** [comment]
> Actually, I want to implement an HTTP proxy agent, and the client will communicate with the node through it.

There is no option to configure a HTTP proxy in the SDK as it relies on the Node network configurations to make read/write calls.

For that, you can either use a custom client and handle the proxy logic in there. Or have a client interact with your HTTP server/proxy and that server will use the SDK to communicate with the node

**Comment by incognito243** [comment]
got u bro, tks for the support
